# Evaluate and Use Models from Model Garden

## Task 2. Prepare prompts for model evaluation

In [1]:
!pip install --upgrade --quiet google-cloud-aiplatform \
    google-cloud-logging litellm 'anthropic[vertex]'

### Setup and Initialize Vertex AI 

Run the following cells to install and import packages and initialize Vertex AI.

In [1]:
import google.cloud.logging
from google.cloud import aiplatform
from IPython.display import Markdown
import logging
import pandas as pd
import random

import vertexai
from vertexai.generative_models import GenerativeModel, GenerationConfig
from vertexai.evaluation import (
    MetricPromptTemplateExamples,
    EvalTask,
    PairwiseMetric,
    PointwiseMetric,
)

# Sets Pandas to display content in wider columns
pd.set_option("display.max_colwidth", None)

# Do not remove logging section
client = google.cloud.logging.Client()
client.setup_logging()

# TODO Add your project and location to initialize vertxai
PROJECT_ID, = !gcloud config get project
LOCATION = "us-central1"

vertexai.init(project=PROJECT_ID, location=LOCATION)

pd.set_option("display.max_colwidth", None)

/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.appengine_logging_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.appengine_logging_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.resourcemanager_v3 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.resourcemanager_v3 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1.schema.predict.instance_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1.schema.predict.instance_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1.schema.predict.params_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1.schema.predict.params_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1.schema.predict.prediction_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1.schema.predict.prediction_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1.schema.trainingjob.definition_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1.schema.trainingjob.definition_v1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1beta1.schema.predict.instance_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1beta1.schema.predict.instance_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1beta1.schema.predict.params_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1beta1.schema.predict.params_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1beta1.schema.predict.prediction_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1beta1.schema.predict.prediction_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.cloud.aiplatform.v1beta1.schema.trainingjob.definition_v1beta1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.aiplatform.v1beta1.schema.trainingjob.definition_v1beta1 past that date.
  warnings.warn(message, FutureWarning)
100%|██████████| 5/5 [00:21<00:00,  2.63s/it]

### Define Prompts for Evaluation

In [2]:
prompt_template = """
    You are a technical architect.

    Prepare a high-level project plan for how a solution to the
    following PROJECT REQUEST could be developed using Google Cloud.
    
    We don't want to begin projects that we can't deliver well in
    under four months, so also weigh in on whether you think this
    is a good time for us to attempt this project.
    
    PROJECT REQUEST:
    {project_request}
"""

In [3]:
project_requests = [
    """
    Inventory Management with Real-time Visibility.
    Retail division needs to track inventory across all physical stores
    and e-commerce channels with real-time accuracy. Key pain point
    is stockouts and overstock leading to lost sales and increased
    holding costs. They're looking for a cloud solution that integrates
    seamlessly with existing POS systems and offers predictive analytics
    for demand forecasting.
    """,
    """
    AI-Driven Material Selection & Performance Prediction.
    Product Development is interested in AI's ability to analyze material properties
    and predict their performance under various conditions within the
    context of their industrial designs. Wants assistance in identifying
    the most suitable and cost-effective materials early in the design process.
    """,
    """
    Optimize Yield & Reduce Input Costs.
    Agriculture department specifically mentioned a desire to increase crop
    output (e.g., by X%) while simultaneously decreasing expenses on water,
    fertilizer, and pesticides (e.g., by Y%) through more precise application
    and predictive insights.
    """,
    """
    Enhanced Predictive Maintenance for Fleet Operations.
    Distribution department expressed a strong need to leverage AI/ML on their
    cloud platform for proactive identification of potential component failures
    across their delivery fleet. Key drivers are reducing unscheduled downtime,
    optimizing maintenance schedules, and minimizing operational disruption.
    Requires ingestion of vast amounts of sensor data (IoT), flight logs, and
    maintenance records.
    """,
    """
    Inaccurate Vehicle Valuation.
    Distribution department struggles with inconsistent and often delayed real-time
    pricing for used vehicles, leading to lost profit margins and slower inventory
    turnover. Needs a solution that leverages AI to provide highly accurate,
    dynamic valuation based on a wide range of data points (market trends,
    condition, history, local demand).
    """

]

In [4]:
# TODO
# Update the code so that the variable `prompts` contains a list of
# strings, applying the `prompt_template` to each item in `project_requests`

prompts = [
    prompt_template.format(project_request=project_request)
    for project_request in project_requests
]

print(prompts[0])

    You are a technical architect.

    Prepare a high-level project plan for how a solution to the
    following PROJECT REQUEST could be developed using Google Cloud.

    We don't want to begin projects that we can't deliver well in
    under four months, so also weigh in on whether you think this
    is a good time for us to attempt this project.

    PROJECT REQUEST:

    Inventory Management with Real-time Visibility.
    Retail division needs to track inventory across all physical stores
    and e-commerce channels with real-time accuracy. Key pain point
    is stockouts and overstock leading to lost sales and increased
    holding costs. They're looking for a cloud solution that integrates
    seamlessly with existing POS systems and offers predictive analytics
    for demand forecasting.

In [5]:
# Check your work

assert len(prompts) == 5, "You don't have a response for each project_request."
assert type(prompts[0]) == str, ("Make sure your prompts are strings.")

## Task 3. Get Qwen3-Next Instruct Responses using the LiteLLM SDK

In [6]:
import os
import litellm

MAX_TOKENS = 1024

In [7]:
# Vertex AI uses application default credentials
# If not using a Vertex AI resource, use 'gcloud auth application-default login' to authenticate
# Here we unpack from the existing env variable GOOGLE_CLOUD_PROJECT
os.environ["VERTEXAI_PROJECT"] = os.environ["GOOGLE_CLOUD_PROJECT"]
os.environ["VERTEXAI_LOCATION"] = "global"

In [8]:
# Non-streaming response
response = litellm.responses(
    model="vertex_ai/qwen/qwen3-next-80b-a3b-instruct-maas",
    input="Tell me a three sentence bedtime story about a unicorn.",
    max_output_tokens=MAX_TOKENS
)

print(response.output[0].content[0].text)

04:26:06 - LiteLLM:INFO: utils.py:3880 -
LiteLLM completion() model= qwen/qwen3-next-80b-a3b-instruct-maas; provider = vertex_ai
04:26:07 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:26:07 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler

Under a velvet sky sprinkled with stars, a tiny silver unicorn named Lumi drifted through the meadow, her horn glowing softly like a whispered wish. She tucked each sleeping animal with a breeze of star-dust—bunnies under clover, owls in their branches—until only the moon remained awake to watch. With a yawn as soft as petals, Lumi curled into a cloud and dreamed of tomorrow’s gentle magic, knowing the world was safe because she believed in it.

In [11]:
import litellm

qwen3_responses = []

for prompt in prompts:
    response = litellm.responses(
        model="vertex_ai/qwen/qwen3-next-80b-a3b-instruct-maas",
        input=prompt,
        max_output_tokens=1024,
    )
    
    # Extract ONLY the text output
    qwen3_responses.append(response.output[0].content[0].text)

04:28:44 - LiteLLM:INFO: utils.py:3880 -
LiteLLM completion() model= qwen/qwen3-next-80b-a3b-instruct-maas; provider = vertex_ai
04:28:48 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:28:48 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:28:48 - LiteLLM:INFO: utils.py:3880 -
LiteLLM completion() model= qwen/qwen3-next-80b-a3b-instruct-maas; provider = vertex_ai
04:28:53 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:28:53 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:28:53 - LiteLLM:INFO: utils.py:3880 -
LiteLLM completion() model= qwen/qwen3-next-80b-a3b-instruct-maas; provider = vertex_ai
04:28:58 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:28:58 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:28:58 - LiteLLM:INFO: utils.py:3880 -
LiteLLM completion() model= qwen/qwen3-next-80b-a3b-instruct-maas; provider = vertex_ai
04:29:02 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:29:02 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:29:02 - LiteLLM:INFO: utils.py:3880 -
LiteLLM completion() model= qwen/qwen3-next-80b-a3b-instruct-maas; provider = vertex_ai
04:29:07 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler
04:29:07 - LiteLLM:INFO: utils.py:1625 - Wrapper: Completed Call, calling success_handler

In [12]:
# Check your work

assert len(prompts) == len(qwen3_responses), "You don't have a response for each prompt."
assert type(qwen3_responses[0]) == str, ("Extract just the text response, "
                                          "not the entire response object.")
# View one response
Markdown(qwen3_responses[0])

Absolutely — as a Technical Architect, I’ll provide a clear, actionable, high-level project plan using **Google Cloud**, along with a go/no-go assessment based on your 4-month delivery constraint.

---

## ✅ **Project Title**:
**Real-Time Inventory Intelligence Platform for Retail (RTIIP)**

### 🎯 **Objective**:
Build a cloud-native, real-time inventory visibility and predictive demand forecasting system that integrates with existing POS systems to eliminate stockouts and overstock, reducing lost sales and holding costs by 20–30% within 6 months of launch.

---

## ✅ **Go/No-Go Assessment: Is This a Good Project to Start Now?**

### **✅ YES — Proceed with Confidence**
**Why?**
- **Scope is focused and achievable within 4 months** (see plan below).
- **Google Cloud provides all necessary building blocks** (real-time ingestion, ML, orchestration, APIs) with minimal custom dev.
- **Retailers universally struggle with this problem** — strong ROI case (reduced stockouts = higher revenue; reduced overstock = lower warehousing costs).
- **Existing POS systems** are likely already generating structured data — integration is feasible via APIs or batch syncs.
- **Cloud-native approach** allows rapid iteration and avoids legacy system lock-in.

### ⚠️ **Critical Success Factors**:
- Must have access to at least **3–6 months of historical sales + inventory data** from POS and warehouse systems.
- Must secure stakeholder buy-in to **enable API access to POS systems** (critical path).
- Design for **phased rollout** — pilot 1–2 stores first.

> ✅ **Verdict**: **Proceed** — this is a high-impact, low-to-moderate complexity project that aligns perfectly with Google Cloud’s strengths and your 4-month window.

---

## 🗺️ **High-Level Project Plan (4-Month Timeline)**

### **Phase 1: Discovery & Architecture Finalization (Weeks 1–3)**
**Goals**: Confirm data sources, define SLAs, finalize architecture.
**Activities**:
- Map existing POS systems (e.g., Square, Shopify, Oracle, SAP) — identify API access points or data export formats (CSV/FTP/DB).
- Audit historical data quality (accuracy, frequency, granularity).
- Define KPIs:
  - Stockout rate (%)
  - Inventory turnover ratio
  - Forecast accuracy (MAPE)
- Finalize architecture (see below).
**Deliverable**: Signed-off architecture diagram + data governance plan.

### **Phase 2: Data Ingestion & Real-Time Pipeline (Weeks 4–7)**
**Goals**: Build a resilient, real-time inventory data pipeline.
**Google Cloud Components**:
- **Cloud Pub/Sub**: Ingest real-time inventory updates from POS and warehouse systems.
- **Cloud Dataflow (Apache Beam)**: Transform and normalize data (e.g., SKU standardization, store mapping).
- **BigQuery**: Central data warehouse — store real-time and historical inventory + sales.
- **Cloud Storage**: Archive raw logs and batch exports.
**Key Integration**:
- Use **Cloud Run** or **App Engine** to build lightweight adapters for each POS system (REST/Webhook).
- Use **Cloud Secret Manager** to securely store API keys.
**Deliverable**: End-to-end pipeline ingesting 10K+ events/hr with <5s latency.

### **Phase 3: Predictive Demand Forecasting (Weeks 8–11)**
**Goals**: Deploy ML model to predict demand at SKU × Store level.
**Google Cloud Components**:
- **BigQuery ML**: Rapid prototyping of time-series models (e.g., ARIMA, Prophet) on historical sales + promotions + seasonality.
- **Vertex AI**: For advanced modeling (LSTMs, ensemble models) if BQ ML is insufficient.
- **Cloud Composer (Airflow)**: Orchestrate daily retraining pipelines (triggered on new sales data).
**Model Inputs**:
- Historical sales (daily)
- Promotions, holidays
- Store location (urban/rural), foot traffic (if available)
- Inventory levels (lagged)
**Output**: Daily SKU-store demand forecast with confidence intervals.
**Deliverable**: Forecast model deployed, validated on historical data (MAPE < 15%).

### **Phase 4: Real-Time Dashboard & Alerts (Weeks 12–15)**
**Goals**: Enable visibility and actionability for store managers and planners.
**Google Cloud Components**:
- **Looker Studio (formerly Data Studio)**: Interactive dashboard showing:
  - Real-time inventory levels per store
  - Forecast vs actual sales
  - Stockout/overstock alerts
- **Cloud Functions**:

## Task 4. Get Claude Responses using the Anthropic SDK

In [13]:
from anthropic import AnthropicVertex

In [19]:
CLAUDE_MODEL = "claude-sonnet-4@20250514"
CLAUDE_LOCATIONS = ["us-east5", "europe-west4", "GLOBAL"]

# TODO
# Implement an anthropic_client to access the Claude Sonnet 4 model
# using the model ID defined above
import ipywidgets as widgets
from IPython.display import display

dropdown = widgets.Dropdown(
    options=CLAUDE_LOCATIONS,
    description="Select a location:",
    font_weight="bold",
    style={"description_width": "initial"},
)


def dropdown_eventhandler(change):
    global LOCATION
    if change["type"] == "change" and change["name"] == "value":
        LOCATION = change.new
        print("Selected:", change.new)


LOCATION = dropdown.value
dropdown.observe(dropdown_eventhandler, names="value")
display(dropdown)

anthropic_client = AnthropicVertex(region=LOCATION, project_id=PROJECT_ID)

Dropdown(description='Select a location:', options=('us-east5', 'europe-west4', 'GLOBAL'), style=DescriptionSt…

In [20]:
claude_responses = []

# TODO
# Update the code below to populate the list claude_responses
# with just the text string of Clade Sonnet 4's response to each prompt

for prompt in prompts:
    message = anthropic_client.messages.create(
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        model=CLAUDE_MODEL,
    )
    print(message.model_dump_json(indent=2))
    claude_response = message.model_dump_json(indent=2)
    claude_responses.append(claude_response)

{
  "id": "msg_vrtx_018nqEW91LUyerpZ5fJfh4z5",
  "content": [
    {
      "citations": null,
      "text": "# High-Level Project Plan: Real-time Inventory Management System\n\n## Executive Summary\nThis project is **feasible within a 4-month timeline** with proper scope management and phased delivery. The Google Cloud ecosystem provides robust, enterprise-ready services that can deliver immediate value while establishing a foundation for advanced analytics.\n\n## Architecture Overview\n\n### Core Google Cloud Services\n- **Cloud SQL** or **Firestore**: Primary inventory database\n- **Pub/Sub**: Real-time event streaming for inventory updates\n- **Cloud Functions**: Serverless integration and business logic\n- **BigQuery**: Data warehouse for analytics and forecasting\n- **Vertex AI**: Machine learning for demand prediction\n- **Cloud Run**: Microservices for API layer\n- **API Gateway**: Secure API management\n- **Cloud Monitoring**: Observability and alerting\n\n## 4-Month Phased Delivery Plan\n\n### Phase 1: Foundation (Month 1)\n**Deliverables:**\n- Core inventory database design and deployment\n- Basic API framework for CRUD operations\n- POS system integration framework\n- Real-time inventory tracking for 2-3 pilot stores\n\n**Key Activities:**\n- Requirements gathering and data mapping\n- Set up Cloud SQL instance with inventory schema\n- Implement Cloud Functions for basic inventory operations\n- Establish Pub/Sub topics for real-time updates\n- Build initial integration with primary POS system\n\n### Phase 2: Integration & Real-time Processing (Month 2)\n**Deliverables:**\n- Complete POS integration across all store formats\n- E-commerce platform integration\n- Real-time inventory synchronization\n- Basic dashboard for inventory visibility\n\n**Key Activities:**\n- Implement remaining POS integrations using Cloud Functions\n- Set up real-time data pipelines with Pub/Sub\n- Deploy Cloud Run services for API layer\n- Build inventory management dashboard\n- Implement stock level alerts and notifications\n\n### Phase 3: Analytics & Intelligence (Month 3)\n**Deliverables:**\n- Historical data migration to BigQuery\n- Basic demand forecasting model\n- Inventory optimization recommendations\n- Advanced reporting and analytics\n\n**Key Activities:**\n- Data pipeline from operational systems to BigQuery\n- Develop initial ML models using Vertex AI\n- Implement predictive analytics for top-selling items\n- Create executive dashboards and reports\n- Set up automated reorder point calculations\n\n### Phase 4: Optimization & Launch (Month 4)\n**Deliverables:**\n- Production-ready system with full monitoring\n- Advanced predictive capabilities\n- Performance optimization\n- User training and documentation\n\n**Key Activities:**\n- Performance tuning and optimization\n- Enhanced ML models for seasonal trends\n- Comprehensive testing and quality assurance\n- User acceptance testing and training\n- Production deployment with monitoring\n\n## Technical Implementation Strategy\n\n### Integration Approach\n1. **API-First Design**: RESTful APIs using Cloud Run for scalability\n2. **Event-Driven Architecture**: Pub/Sub for real-time inventory updates\n3. **Microservices**: Separate services for inventory, forecasting, and reporting\n4. **Data Lake Strategy**: Raw data in Cloud Storage, processed data in BigQuery\n\n### Key Integrations\n- **POS Systems**: Cloud Functions with appropriate connectors\n- **E-commerce Platforms**: API integrations via Cloud Run services\n- **ERP Systems**: Batch and real-time sync capabilities\n- **External Data**: Weather, events, and market data for enhanced forecasting\n\n## Risk Assessment & Mitigation\n\n### High Risks\n1. **POS Integration Complexity**\n   - *Mitigation*: Start with pilot stores, use established connectors where possible\n2. **Data Quality Issues**\n   - *Mitigation*: Implement data validation and cleansing in Cloud Functions\n3. **Real-time Performance Requirements**\n   - *Mitigation*: Use Pub/Sub for async processing, implement caching strategies\n\n### Medium Risks\n1. **ML Model Accuracy**\n   - *Mitigation*: Start with simple models, iterate based on feedback\n2. **User Adoption**\n   - *Mitigation*: Involve key users in design, provide comprehensive training\n\n## Success Metrics\n- **Inventory Accuracy**: >95% real-time accuracy\n- **Stockout Reduction**: 30% decrease in stockouts\n- **Forecast Accuracy**: 80% accuracy for 30-day demand prediction\n- **System Performance**: <2 second response times for inventory queries\n\n## Resource Requirements\n- **Technical Team**: 1 Cloud Architect, 2 Full-stack Developers,",
      "type": "text"
    }
  ],
  "model": "claude-sonnet-4-20250514",
  "role": "assistant",
  "stop_reason": "max_tokens",
  "stop_sequence": null,
  "type": "message",
  "usage": {
    "cache_creation": {
      "ephemeral_1h_input_tokens": 0,
      "ephemeral_5m_input_tokens": 0
    },
    "cache_creation_input_tokens": 0,
    "cache_read_input_tokens": 0,
    "input_tokens": 193,
    "output_tokens": 1024,
    "server_tool_use": null,
    "service_tier": null
  }
}
{
  "id": "msg_vrtx_01PTUVJXuJz8JumNRA9z57DD",
  "content": [
    {
      "citations": null,
      "text": "# AI-Driven Material Selection & Performance Prediction - Project Plan\n\n## Executive Summary & Feasibility Assessment\n\n**Recommendation: PROCEED with phased approach**\n\nThis project is feasible within 4 months if we focus on a well-defined scope with existing material databases and proven ML techniques. The key is starting with a specific use case (e.g., structural materials for specific applications) rather than attempting to solve all material selection problems.\n\n## High-Level Architecture (Google Cloud)\n\n```\nData Layer → ML Pipeline → Prediction Engine → User Interface\n```\n\n### Core Components:\n- **Vertex AI** for ML model development and deployment\n- **BigQuery** for material property data warehouse\n- **Cloud Storage** for raw data and model artifacts\n- **Cloud Run** for API services\n- **Firebase/App Engine** for web interface\n\n## 4-Month Project Plan\n\n### Phase 1: Foundation (Month 1)\n**Weeks 1-2: Requirements & Data Strategy**\n- Define specific material categories and performance metrics\n- Identify and acquire material property datasets\n- Set up Google Cloud infrastructure\n- Establish data ingestion pipeline to BigQuery\n\n**Weeks 3-4: Data Pipeline Development**\n- Implement ETL processes using Dataflow\n- Create material property data models in BigQuery\n- Develop data quality and validation frameworks\n- Begin exploratory data analysis\n\n### Phase 2: ML Development (Month 2)\n**Weeks 5-6: Feature Engineering**\n- Identify key material properties for prediction\n- Engineer features for performance prediction models\n- Create training/validation datasets\n- Set up Vertex AI ML workflows\n\n**Weeks 7-8: Model Development**\n- Train regression models for performance prediction\n- Develop classification models for material suitability\n- Implement model evaluation and validation\n- Create model versioning and experiment tracking\n\n### Phase 3: Prediction Engine (Month 3)\n**Weeks 9-10: Model Optimization**\n- Hyperparameter tuning using Vertex AI\n- Model ensemble and validation\n- Performance optimization for inference\n- Create model deployment pipeline\n\n**Weeks 11-12: API Development**\n- Build REST APIs using Cloud Run\n- Implement material recommendation engine\n- Create performance prediction services\n- Develop cost optimization algorithms\n\n### Phase 4: Integration & Deployment (Month 4)\n**Weeks 13-14: User Interface**\n- Develop web application (App Engine/Firebase)\n- Create material selection workflow\n- Implement visualization for predictions\n- Build reporting and export capabilities\n\n**Weeks 15-16: Testing & Launch**\n- User acceptance testing with Product Development\n- Performance testing and optimization\n- Documentation and training materials\n- Production deployment and monitoring\n\n## Technical Stack\n\n### Data & Storage\n- **BigQuery**: Material properties, historical performance data\n- **Cloud Storage**: Raw datasets, model artifacts\n- **Firestore**: User preferences, application state\n\n### ML & AI\n- **Vertex AI**: Model training, hyperparameter tuning, deployment\n- **AutoML Tables**: For rapid prototyping\n- **TensorFlow/Scikit-learn**: Custom model development\n- **Vertex AI Predictions**: Real-time inference\n\n### Application Layer\n- **Cloud Run**: Containerized ML APIs\n- **App Engine**: Web application hosting\n- **Cloud Functions**: Event-driven processing\n- **Load Balancer**: Traffic distribution\n\n### Monitoring & Security\n- **Cloud Monitoring**: Performance metrics\n- **Cloud Logging**: Application logs\n- **IAM**: Access control\n- **Secret Manager**: API keys and credentials\n\n## Key Deliverables\n\n1. **Material Property Database**: Structured repository of material characteristics\n2. **Performance Prediction Models**: ML models for various performance metrics\n3. **Material Recommendation API**: Service for suggesting optimal materials\n4. **Cost Optimization Engine**: Algorithm balancing performance vs. cost\n5. **Web Application**: User interface for material selection workflow\n6. **Integration APIs**: Endpoints for CAD/design tool integration\n\n## Success Metrics\n\n- **Prediction Accuracy**: >85% accuracy for performance predictions\n- **Recommendation Quality**: >80% user satisfaction with suggestions\n- **Response Time**: <2 seconds for material recommendations\n- **Cost Savings**: Demonstrable reduction in material testing costs\n- **User Adoption**: 70% of Product Development team actively using system\n\n## Risk Mitigation\n\n### High Risks:\n1. **Data Quality/Availability**: \n   - Mitigation: Partner with material suppliers for data access\n   - Fallback: Use publicly available databases (NIST, AS",
      "type": "text"
    }
  ],
  "model": "claude-sonnet-4-20250514",
  "role": "assistant",
  "stop_reason": "max_tokens",
  "stop_sequence": null,
  "type": "message",
  "usage": {
    "cache_creation": {
      "ephemeral_1h_input_tokens": 0,
      "ephemeral_5m_input_tokens": 0
    },
    "cache_creation_input_tokens": 0,
    "cache_read_input_tokens": 0,
    "input_tokens": 169,
    "output_tokens": 1024,
    "server_tool_use": null,
    "service_tier": null
  }
}
{
  "id": "msg_vrtx_0113py5kfNhGHGDArhCXSJaE",
  "content": [
    {
      "citations": null,
      "text": "# High-Level Project Plan: Agricultural Optimization Platform\n\n## Executive Summary\n\nThis project aims to develop a precision agriculture platform using IoT sensors, machine learning, and data analytics to optimize crop yields while reducing input costs. Based on scope and complexity, I **recommend proceeding** with a phased 4-month approach focusing on MVP delivery.\n\n## Project Feasibility Assessment ✅ **RECOMMENDED**\n\n**Timeline: Achievable in 4 months** with proper scoping\n- **Phase 1 (MVP)**: Core monitoring and basic optimization\n- **Future phases**: Advanced ML models and expanded crop types\n\n**Key success factors:**\n- Start with 1-2 crop types and limited field area\n- Leverage existing GCP ML services rather than building from scratch\n- Partner with agricultural domain experts\n- Use proven IoT hardware solutions\n\n## High-Level Architecture\n\n```\nField Sensors → IoT Core → Cloud Functions → BigQuery\n                                    ↓\nWeather APIs → Dataflow → AI/ML Platform → Recommendations API\n                                    ↓\nHistorical Data → Vertex AI → Dashboard (Cloud Run)\n```\n\n## Phase 1: MVP Delivery (4 months)\n\n### Month 1: Foundation & Data Collection\n**Week 1-2: Infrastructure Setup**\n- Set up GCP project with proper IAM and billing\n- Deploy IoT Core for sensor data ingestion\n- Configure BigQuery data warehouse\n- Set up Cloud Monitoring and logging\n\n**Week 3-4: Sensor Integration**\n- Deploy soil moisture, pH, and NPK sensors\n- Integrate weather station data\n- Set up data pipeline using Cloud Functions\n- Implement data validation and quality checks\n\n### Month 2: Data Pipeline & Analytics\n**Week 5-6: Data Processing**\n- Build Dataflow pipelines for real-time processing\n- Integrate external weather APIs (Google Weather API)\n- Set up historical agricultural data imports\n- Implement data cleansing and normalization\n\n**Week 7-8: Basic Analytics**\n- Create BigQuery views for agricultural insights\n- Build initial Looker dashboards\n- Implement alerting for critical thresholds\n- Basic correlation analysis setup\n\n### Month 3: ML Model Development\n**Week 9-10: Model Training**\n- Use Vertex AI AutoML for crop yield prediction\n- Develop irrigation optimization models\n- Create fertilizer recommendation algorithms\n- Train pest/disease detection models (image-based)\n\n**Week 11-12: Model Integration**\n- Deploy models using Vertex AI Endpoints\n- Build recommendation engine API (Cloud Run)\n- Implement A/B testing framework\n- Create model monitoring and retraining pipelines\n\n### Month 4: Application & Optimization\n**Week 13-14: User Interface**\n- Deploy farmer-facing dashboard (Cloud Run)\n- Mobile-responsive interface for field technicians\n- Implement recommendation delivery system\n- Set up notification systems (SMS/email)\n\n**Week 15-16: Testing & Launch**\n- User acceptance testing with agricultural partners\n- Performance optimization and security review\n- Documentation and training materials\n- Production deployment and monitoring setup\n\n## Core Google Cloud Components\n\n### Data & Analytics Stack\n- **IoT Core**: Sensor data ingestion\n- **BigQuery**: Data warehouse and analytics\n- **Dataflow**: Stream and batch processing\n- **Cloud Storage**: Raw data and model artifacts\n- **Looker**: Business intelligence dashboards\n\n### AI/ML Platform\n- **Vertex AI**: ML model training and deployment\n- **AutoML**: Rapid model development\n- **Vision AI**: Crop disease detection from images\n- **Document AI**: Processing agricultural reports\n\n### Application Platform\n- **Cloud Run**: Microservices and web applications\n- **Cloud Functions**: Event-driven processing\n- **Firebase**: Real-time notifications\n- **Cloud CDN**: Global content delivery\n\n### Integration & Security\n- **Cloud Endpoints**: API management\n- **Identity & Access Management**: Security controls\n- **Cloud Monitoring**: System observability\n- **Cloud Scheduler**: Automated tasks\n\n## Key Features (MVP Scope)\n\n### 🌱 **Yield Optimization**\n- Soil health monitoring and recommendations\n- Optimal planting density suggestions\n- Growth stage tracking and predictions\n- Harvest timing optimization\n\n### 💧 **Water Management**\n- Precision irrigation scheduling\n- Soil moisture-based watering recommendations\n- Weather-integrated irrigation planning\n- Water usage analytics and reduction tracking\n\n### 🧪 **Input Cost Reduction**\n- Variable-rate fertilizer application maps\n- Nutrient deficiency early detection",
      "type": "text"
    }
  ],
  "model": "claude-sonnet-4-20250514",
  "role": "assistant",
  "stop_reason": "max_tokens",
  "stop_sequence": null,
  "type": "message",
  "usage": {
    "cache_creation": {
      "ephemeral_1h_input_tokens": 0,
      "ephemeral_5m_input_tokens": 0
    },
    "cache_creation_input_tokens": 0,
    "cache_read_input_tokens": 0,
    "input_tokens": 172,
    "output_tokens": 1024,
    "server_tool_use": null,
    "service_tier": null
  }
}
{
  "id": "msg_vrtx_01D6ub6VrPr7Ui4VxWAQE4H2",
  "content": [
    {
      "citations": null,

In [21]:
# Check your work

assert len(prompts) == len(claude_responses), "You don't have a response for each prompt."
assert type(claude_responses[0]) == str, ("Extract just the text response, "
                                          "not the entire response object.")

# View one response
Markdown(claude_responses[0])

{
  "id": "msg_vrtx_018nqEW91LUyerpZ5fJfh4z5",
  "content": [
    {
      "citations": null,
      "text": "# High-Level Project Plan: Real-time Inventory Management System\n\n## Executive Summary\nThis project is **feasible within a 4-month timeline** with proper scope management and phased delivery. The Google Cloud ecosystem provides robust, enterprise-ready services that can deliver immediate value while establishing a foundation for advanced analytics.\n\n## Architecture Overview\n\n### Core Google Cloud Services\n- **Cloud SQL** or **Firestore**: Primary inventory database\n- **Pub/Sub**: Real-time event streaming for inventory updates\n- **Cloud Functions**: Serverless integration and business logic\n- **BigQuery**: Data warehouse for analytics and forecasting\n- **Vertex AI**: Machine learning for demand prediction\n- **Cloud Run**: Microservices for API layer\n- **API Gateway**: Secure API management\n- **Cloud Monitoring**: Observability and alerting\n\n## 4-Month Phased Delivery Plan\n\n### Phase 1: Foundation (Month 1)\n**Deliverables:**\n- Core inventory database design and deployment\n- Basic API framework for CRUD operations\n- POS system integration framework\n- Real-time inventory tracking for 2-3 pilot stores\n\n**Key Activities:**\n- Requirements gathering and data mapping\n- Set up Cloud SQL instance with inventory schema\n- Implement Cloud Functions for basic inventory operations\n- Establish Pub/Sub topics for real-time updates\n- Build initial integration with primary POS system\n\n### Phase 2: Integration & Real-time Processing (Month 2)\n**Deliverables:**\n- Complete POS integration across all store formats\n- E-commerce platform integration\n- Real-time inventory synchronization\n- Basic dashboard for inventory visibility\n\n**Key Activities:**\n- Implement remaining POS integrations using Cloud Functions\n- Set up real-time data pipelines with Pub/Sub\n- Deploy Cloud Run services for API layer\n- Build inventory management dashboard\n- Implement stock level alerts and notifications\n\n### Phase 3: Analytics & Intelligence (Month 3)\n**Deliverables:**\n- Historical data migration to BigQuery\n- Basic demand forecasting model\n- Inventory optimization recommendations\n- Advanced reporting and analytics\n\n**Key Activities:**\n- Data pipeline from operational systems to BigQuery\n- Develop initial ML models using Vertex AI\n- Implement predictive analytics for top-selling items\n- Create executive dashboards and reports\n- Set up automated reorder point calculations\n\n### Phase 4: Optimization & Launch (Month 4)\n**Deliverables:**\n- Production-ready system with full monitoring\n- Advanced predictive capabilities\n- Performance optimization\n- User training and documentation\n\n**Key Activities:**\n- Performance tuning and optimization\n- Enhanced ML models for seasonal trends\n- Comprehensive testing and quality assurance\n- User acceptance testing and training\n- Production deployment with monitoring\n\n## Technical Implementation Strategy\n\n### Integration Approach\n1. **API-First Design**: RESTful APIs using Cloud Run for scalability\n2. **Event-Driven Architecture**: Pub/Sub for real-time inventory updates\n3. **Microservices**: Separate services for inventory, forecasting, and reporting\n4. **Data Lake Strategy**: Raw data in Cloud Storage, processed data in BigQuery\n\n### Key Integrations\n- **POS Systems**: Cloud Functions with appropriate connectors\n- **E-commerce Platforms**: API integrations via Cloud Run services\n- **ERP Systems**: Batch and real-time sync capabilities\n- **External Data**: Weather, events, and market data for enhanced forecasting\n\n## Risk Assessment & Mitigation\n\n### High Risks\n1. **POS Integration Complexity**\n   - *Mitigation*: Start with pilot stores, use established connectors where possible\n2. **Data Quality Issues**\n   - *Mitigation*: Implement data validation and cleansing in Cloud Functions\n3. **Real-time Performance Requirements**\n   - *Mitigation*: Use Pub/Sub for async processing, implement caching strategies\n\n### Medium Risks\n1. **ML Model Accuracy**\n   - *Mitigation*: Start with simple models, iterate based on feedback\n2. **User Adoption**\n   - *Mitigation*: Involve key users in design, provide comprehensive training\n\n## Success Metrics\n- **Inventory Accuracy**: >95% real-time accuracy\n- **Stockout Reduction**: 30% decrease in stockouts\n- **Forecast Accuracy**: 80% accuracy for 30-day demand prediction\n- **System Performance**: <2 second response times for inventory queries\n\n## Resource Requirements\n- **Technical Team**: 1 Cloud Architect, 2 Full-stack Developers,",
      "type": "text"
    }
  ],
  "model": "claude-sonnet-4-20250514",
  "role": "assistant",
  "stop_reason": "max_tokens",
  "stop_sequence": null,
  "type": "message",
  "usage": {
    "cache_creation": {
      "ephemeral_1h_input_tokens": 0,
      "ephemeral_5m_input_tokens": 0
    },
    "cache_creation_input_tokens": 0,
    "cache_read_input_tokens": 0,
    "input_tokens": 193,
    "output_tokens": 1024,
    "server_tool_use": null,
    "service_tier": null
  }
}

## Task 5. Conduct a pairwise evaluation

### Explore Metrics and Select Evaluation Criteria

In [22]:
MetricPromptTemplateExamples.list_example_metric_names()

['coherence',
 'fluency',
 'safety',
 'groundedness',
 'instruction_following',
 'verbosity',
 'text_quality',
 'summarization_quality',
 'question_answering_quality',
 'multi_turn_chat_quality',
 'multi_turn_safety',
 'pairwise_coherence',
 'pairwise_fluency',
 'pairwise_safety',
 'pairwise_groundedness',
 'pairwise_instruction_following',
 'pairwise_verbosity',
 'pairwise_text_quality',
 'pairwise_summarization_quality',
 'pairwise_question_answering_quality',
 'pairwise_multi_turn_chat_quality',
 'pairwise_multi_turn_safety']

In [23]:
print(MetricPromptTemplateExamples.Pairwise.TEXT_QUALITY.metric_prompt_template)

# Instruction
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by two AI models. We will provide you with the user input and a pair of AI-generated responses (Response A and Response B). You should first read the user input carefully for analyzing the task, and then evaluate the quality of the responses based on the Criteria provided in the Evaluation section below.
You will first judge responses individually, following the Rating Rubric and Evaluation Steps. Then you will give step-by-step explanations for your judgment, compare the results to declare the winner based on the Rating Rubric and Evaluation Steps.

# Evaluation
## Metric Definition
You will be assessing the Text Quality of each model's response, which measures how effectively the text conveys clear, accurate, and engaging information that directly addresses the user's prompt, considering factors like fluency, coherence, relevance, and conciseness.

## Criteria
Coherence: The response presents ideas in a logical and organized manner, with clear transitions and a consistent focus, making it easy to follow and understand.
Fluency: The text flows smoothly and naturally, adhering to grammatical rules and using appropriate vocabulary.
Instruction following: The response demonstrates a clear understanding of the task instructions, satisfying all of the instruction's requirements.
Groundedness: The response contains information included only in the context. The response does not reference any outside information.
Verbosity: The response is appropriately concise, providing sufficient detail without using complex language to thoroughly address the prompt without being overly wordy or excessively brief.

## Rating Rubric
"A": Response A demonstrates significantly better Text Quality than Response B as per criteria, excelling in aspects such as coherence, fluency, instruction following, groundedness, and verbosity.
"SAME": Response A and Response B demonstrate comparable Text Quality as per criteria, with no significant differences in aspects such as coherence, fluency, instruction following, groundedness, and verbosity.
"B": Response B demonstrates significantly better Text Quality than Response A as per criteria, excelling in aspects such as coherence, fluency, instruction following, groundedness, and verbosity.


## Evaluation Steps
STEP 1: Analyze Response A based on all the Criteria provided, including Coherence, Fluency, Instruction following, Groundedness, and Verbosity. Provide assessment according to each criterion.
STEP 2: Analyze Response B based on all the Criteria provided, including Coherence, Fluency, Instruction following, Groundedness, and Verbosity. Provide assessment according to each criterion.
STEP 3: Compare the overall performance of Response A and Response B based on your analyses and assessment of each criterion.
STEP 4: Output your preference of "A", "SAME" or "B" to the pairwise_choice field according to the Rating Rubric.
STEP 5: Output your assessment reasoning in the explanation field, justifying your choice by highlighting the specific strengths and weaknesses of each response in terms of Text Quality.


# User Inputs and AI-generated Responses
## User Inputs
### Prompt
{prompt}

# AI-generated Responses

### Response A
{baseline_model_response}

### Response B
{response}

### Prepare and Execute the Evaluation Task

In [26]:
# TODO
# Provide all the variables required for the metric
# selected above

eval_dataset=pd.DataFrame(
    {
        "prompt": ["prompt0", "prompt1"],
    }
)
eval_dataset = pd.DataFrame(
    {
        "prompt": prompts,
        "baseline_model_response": qwen3_responses,
        "response": claude_responses,
    }
)

eval_dataset.head(1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           prompt  \
0  \n    You are a technical architect.\n\n    Prepare a high-level project plan for how a solution to the\n    following PROJECT REQUEST could be developed using Google Cloud.\n    \n    We don't want to begin projects that we can't deliver well in\n    under four months, so also weigh in on whether you think this\n    is a good time for us to attempt this project.\n    \n    PROJECT REQUEST:\n    \n    Inventory Management with Real-time Visibility.\n    Retail division needs to track inventory across all physical stores\n    and e-commerce channels with real-time accuracy. Key pain point\n    is stockouts and overstock leading to lost sales and increased\n    holding costs. They're looking for a cloud solution that integrates\n    seamlessly with existing POS systems and offers predictive analytics\n    for demand forecasting.\n    \n

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     baseline_model_response  \
0  Absolutely — as a Technical Architect, I’ll provide a clear, actionable, high-level project plan using **Google Cloud**, along with a go/no-go assessment based on your 4-month delivery constraint.\n\n---\n\n## ✅ **Project Title**:  \n**Real-Time Inventory Intelligence Platform for Retail (RTIIP)**\n\n### 🎯 **Objective**:  \nBuild a cloud-native, real-time inventory visibility and predictive demand forecasting system that integrates with existing POS systems to eliminate stockouts and overstock, reducing lost sales and holding costs by 20–30% within 6 months of launch.\n\n---\n\n## ✅ **Go/No-Go Assessment: Is This a Good Project to Start Now?**\n\n### **✅ YES — Proceed with Confidence**  \n**Why?**  \n- **Scope is focused and achievable within 4 months** (see plan below).  \n- **Google Cloud provides all necessary building blocks** (real-time ingestion, ML, orchestration, APIs) with minimal custom dev.  \n- **Retailers universally struggle with this problem** — strong ROI case (reduced stockouts = higher revenue; reduced overstock = lower warehousing costs).  \n- **Existing POS systems** are likely already generating structured data — integration is feasible via APIs or batch syncs.  \n- **Cloud-native approach** allows rapid iteration and avoids legacy system lock-in.\n\n### ⚠️ **Critical Success Factors**:  \n- Must have access to at least **3–6 months of historical sales + inventory data** from POS and warehouse systems.  \n- Must secure stakeholder buy-in to **enable API access to POS systems** (critical path).  \n- Design for **phased rollout** — pilot 1–2 stores first.\n\n> ✅ **Verdict**: **Proceed** — this is a high-impact, low-to-moderate complexity project that aligns perfectly with Google Cloud’s strengths and your 4-month window.\n\n---\n\n## 🗺️ **High-Level Project Plan (4-Month Timeline)**\n\n### **Phase 1: Discovery & Architecture Finalization (Weeks 1–3)**  \n**Goals**: Confirm data sources, define SLAs, finalize architecture.  \n**Activities**:  \n- Map existing POS systems (e.g., Square, Shopify, Oracle, SAP) — identify API access points or data export formats (CSV/FTP/DB).  \n- Audit historical data quality (accuracy, frequency, granularity).  \n- Define KPIs:  \n  - Stockout rate (%)  \n  - Inventory turnover ratio  \n  - Forecast accuracy (MAPE)  \n- Finalize architecture (see below).  \n**Deliverable**: Signed-off architecture diagram + data governance plan.\n\n### **Phase 2: Data Ingestion & Real-Time Pipeline (Weeks 4–7)**  \n**Goals**: Build a resilient, real-time inventory data pipeline.  \n**Google Cloud Components**:  \n- **Cloud Pub/Sub**: Ingest real-time inventory updates from POS and warehouse systems.  \n- **Cloud Dataflow (Apache Beam)**: Transform and normalize data (e.g., SKU standardization, store mapping).  \n- **BigQuery**: Central data warehouse — store real-time and historical inventory + sales.  \n- **Cloud Storage**: Archive raw logs and batch exports.  \n**Key Integration**:  \n- Use **Cloud Run** or **App Engine** to build lightweight adapters for each POS system (REST/Webhook).  \n- Use **Cloud Secret Manager** to securely store API keys.  \n**Deliverable**: End-to-end pipeline ingesting 10K+ events/hr with <5s latency.\n\n### **Phase 3: Predictive Demand Forecasting (Weeks 8–11)**  \n**Goals**: Deploy ML model to predict demand at SKU × Store level.  \n**Google Cloud Components**:  \n- **BigQuery ML**: Rapid prototyping of time-series models (e.g., ARIMA, Prophet) on historical sales + promotions + seasonality.  \n- **Vertex AI**: For advanced modeling (LSTMs, ensemble models) if BQ ML is insufficient.  \n- **Cloud Composer (Airflow)**: Orchestrate daily retraining pipelines (triggered on new sales data).  \n**Model Inputs**:  \n- Historical sales (daily)  \n- Promotions, holidays  \n- Store location (urban/rural), foot traffic (if available)  \n- Inventory levels (lagged)  \n**Output**: Daily SKU-store demand forecast with confidence intervals.  \n**Deliverable**: Forecast model deployed, validated on historical data (MAPE < 15%).\n\n### **Phase 4: Real-Time Dashboard & Alerts (Weeks 12–15)**  \n**Goals**: Enable visibility and actionability for store managers and planners.  \n**Google Cloud Components**:  \n- **Looker Studio (formerly Data Studio)**: Interactive dashboard showing:  \n  - Real-time inventory levels per store  \n  - Forecast vs actual sales  \n  - Stockout/overstock alerts  \n- **Cloud Functions**:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      response

In [27]:
selected_metric = MetricPromptTemplateExamples.Pairwise.TEXT_QUALITY

# TODO
# Complete the definition of the EvalTask using the dataset defined
# above and the selected metric. Keep the provided experiment name.

# pairwise_eval_task = EvalTask(
#     experiment="pairwise-text-quality-001",
# )
pairwise_eval_task = EvalTask(
    dataset=eval_dataset,
    metrics=[selected_metric],
    experiment="pairwise-text-quality-001",
)

In [28]:
pairwise_result = pairwise_eval_task.evaluate()

Associating projects/5399527077/locations/us-central1/metadataStores/default/contexts/pairwise-text-quality-001-52a31f59-36c4-42e0-9ebb-72da2657e5f8 to Experiment: pairwise-text-quality-001

Computing metrics with a total of 5 Vertex Gen AI Evaluation Service API requests.

100%|██████████| 5/5 [00:21<00:00,  4.36s/it]

All 5 metric requests are successfully computed.
Evaluation Took:21.908645441999397 seconds

In [29]:
# TODO
# Display the result's summary_metrics
pairwise_result.summary_metrics

{'row_count': 5,
 'pairwise_text_quality/candidate_model_win_rate': np.float64(0.0),
 'pairwise_text_quality/baseline_model_win_rate': np.float64(1.0)}

In [30]:
# TODO
# Display the result's metrics_table table
pairwise_result.metrics_table

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        prompt  \
0                                               \n    You are a technical architect.\n\n    Prepare a high-level project plan for how a solution to the\n    following PROJECT REQUEST could be developed using Google Cloud.\n    \n    We don't want to begin projects that we can't deliver well in\n    under four months, so also weigh in on whether you think this\n    is a good time for us to attempt this project.\n    \n    PROJECT REQUEST:\n    \n    Inventory Management with Real-time Visibility.\n    Retail division needs to track inventory across all physical stores\n    and e-commerce channels with real-time accuracy. Key pain point\n    is stockouts and overstock leading to lost sales and increased\n    holding costs. They're looking for a cloud solution that integrates\n    seamlessly with existing POS systems and offers predictive analytics\n    for demand forecasting.\n    \n
1                                                                                                                  \n    You are a technical architect.\n\n    Prepare a high-level project plan for how a solution to the\n    following PROJECT REQUEST could be developed using Google Cloud.\n    \n    We don't want to begin projects that we can't deliver well in\n    under four months, so also weigh in on whether you think this\n    is a good time for us to attempt this project.\n    \n    PROJECT REQUEST:\n    \n    AI-Driven Material Selection & Performance Prediction.\n    Product Development is interested in AI's ability to analyze material properties\n    and predict their performance under various conditions within the\n    context of their industrial designs. Wants assistance in identifying\n    the most suitable and cost-effective materials early in the design process.\n    \n
2                                                                                                                                                                                     \n    You are a technical architect.\n\n    Prepare a high-level project plan for how a solution to the\n    following PROJECT REQUEST could be developed using Google Cloud.\n    \n    We don't want to begin projects that we can't deliver well in\n    under four months, so also weigh in on whether you think this\n    is a good time for us to attempt this project.\n    \n    PROJECT REQUEST:\n    \n    Optimize Yield & Reduce Input Costs.\n    Agriculture department specifically mentioned a desire to increase crop\n    output (e.g., by X%) while simultaneously decreasing expenses on water,\n    fertilizer, and pesticides (e.g., by Y%) through more precise application\n    and predictive insights.\n    \n
3  \n    You are a technical architect.\n\n    Prepare a high-level project plan for how a solution to the\n    following PROJECT REQUEST could be developed using Google Cloud.\n    \n    We don't want to begin projects that we can't deliver well in\n    under four months, so also weigh in on whether you think this\n    is a good time for us to attempt this project.\n    \n    PROJECT REQUEST:\n    \n    Enhanced Predictive Maintenance for Fleet Operations.\n    Distribution department expressed a strong need to leverage AI/ML on their\n    cloud platform for proactive identification of potential component failures\n    across their delivery fleet. Key drivers are reducing unscheduled downtime,\n    optimizing maintenance schedules, and minimizing operational disruption.\n    Requires ingestion of vast amounts of sensor data (IoT), flight logs, and\n    maintenance records.\n    \n
4                                                                                        \n    You are a technical architect.\n\n    Prepare a high-level project plan for how a solution to the\n    following PROJECT REQUEST could be developed using Google Cloud.\n    \n    We don't want to begin projects that we can't deliver well in\n    under four months, so also weigh in on whether you think this\n    is a good time for us to attempt this project.\n    \n    PROJECT REQUEST:\n    \n    Inaccurate Vehicle Valuation.\n    Distribution department struggles with inconsistent and often delayed real-time\n    pricing for used vehicles, leading to lost profit margins and slower inventory\n    turnover. Needs a solution that leverages AI to provide highly accurate,\n    dynamic valuation based on a wide range of data points (market trends,\n    condition, history, local demand).\n    \n

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     baseline_model_response  \
0  Absolutely — as a Technical Architect, I’ll provide a clear, actionable, high-level project plan using **Google Cloud**, along with a go/no-go assessment based on your 4-month delivery constraint.\n\n---\n\n## ✅ **Project Title**:  \n**Real-Time Inventory Intelligence Platform for Retail (RTIIP)**\n\n### 🎯 **Objective**:  \nBuild a cloud-native, real-time inventory visibility and predictive demand forecasting system that integrates with existing POS systems to eliminate stockouts and overstock, reducing lost sales and holding costs by 20–30% within 6 months of launch.\n\n---\n\n## ✅ **Go/No-Go Assessment: Is This a Good Project to Start Now?**\n\n### **✅ YES — Proceed with Confidence**  \n**Why?**  \n- **Scope is focused and achievable within 4 months** (see plan below).  \n- **Google Cloud provides all necessary building blocks** (real-time ingestion, ML, orchestration, APIs) with minimal custom dev.  \n- **Retailers universally struggle with this problem** — strong ROI case (reduced stockouts = higher revenue; reduced overstock = lower warehousing costs).  \n- **Existing POS systems** are likely already generating structured data — integration is feasible via APIs or batch syncs.  \n- **Cloud-native approach** allows rapid iteration and avoids legacy system lock-in.\n\n### ⚠️ **Critical Success Factors**:  \n- Must have access to at least **3–6 months of historical sales + inventory data** from POS and warehouse systems.  \n- Must secure stakeholder buy-in to **enable API access to POS systems** (critical path).  \n- Design for **phased rollout** — pilot 1–2 stores first.\n\n> ✅ **Verdict**: **Proceed** — this is a high-impact, low-to-moderate complexity project that aligns perfectly with Google Cloud’s strengths and your 4-month window.\n\n---\n\n## 🗺️ **High-Level Project Plan (4-Month Timeline)**\n\n### **Phase 1: Discovery & Architecture Finalization (Weeks 1–3)**  \n**Goals**: Confirm data sources, define SLAs, finalize architecture.  \n**Activities**:  \n- Map existing POS systems (e.g., Square, Shopify, Oracle, SAP) — identify API access points or data export formats (CSV/FTP/DB).  \n- Audit historical data quality (accuracy, frequency, granularity).  \n- Define KPIs:  \n  - Stockout rate (%)  \n  - Inventory turnover ratio  \n  - Forecast accuracy (MAPE)  \n- Finalize architecture (see below).  \n**Deliverable**: Signed-off architecture diagram + data governance plan.\n\n### **Phase 2: Data Ingestion & Real-Time Pipeline (Weeks 4–7)**  \n**Goals**: Build a resilient, real-time inventory data pipeline.  \n**Google Cloud Components**:  \n- **Cloud Pub/Sub**: Ingest real-time inventory updates from POS and warehouse systems.  \n- **Cloud Dataflow (Apache Beam)**: Transform and normalize data (e.g., SKU standardization, store mapping).  \n- **BigQuery**: Central data warehouse — store real-time and historical inventory + sales.  \n- **Cloud Storage**: Archive raw logs and batch exports.  \n**Key Integration**:  \n- Use **Cloud Run** or **App Engine** to build lightweight adapters for each POS system (REST/Webhook).  \n- Use **Cloud Secret Manager** to securely store API keys.  \n**Deliverable**: End-to-end pipeline ingesting 10K+ events/hr with <5s latency.\n\n### **Phase 3: Predictive Demand Forecasting (Weeks 8–11)**  \n**Goals**: Deploy ML model to predict demand at SKU × Store level.  \n**Google Cloud Components**:  \n- **BigQuery ML**: Rapid prototyping of time-series models (e.g., ARIMA, Prophet) on historical sales + promotions + seasonality.  \n- **Vertex AI**: For advanced modeling (LSTMs, ensemble models) if BQ ML is insufficient.  \n- **Cloud Composer (Airflow)**: Orchestrate daily retraining pipelines (triggered on new sales data).  \n**Model Inputs**:  \n- Historical sales (daily)  \n- Promotions, holidays  \n- Store location (urban/rural), foot traffic (if available)  \n- Inventory levels (lagged)  \n**Output**: Daily SKU-store demand forecast with confidence intervals.  \n**Deliverable**: Forecast model deployed, validated on historical data (MAPE < 15%).\n\n### **Phase 4: Real-Time Dashboard & Alerts (Weeks 12–15)**  \n**Goals**: Enable visibility and actionability for store managers and planners.  \n**Google Cloud Components**:  \n- **Looker Studio (formerly Data Studio)**: Interactive dashboard showing:  \n  - Real-time inventory levels per store  \n  - Forecast vs actual sales  \n  - Stockout/overstock alerts  \n- **Cloud Functions**:
1                                                                                                                                                                                                    Absolutely — as a Technical Architect, I’ll provide a high-level, realistic, and Google Cloud-optimized project plan for **AI-Driven Material Selection & Performance Prediction**, along with a go/no-go assessment based on your 4-month delivery constraint.\n\n---\n\n## ✅ **Project Assessment: Is This a Good Time to Start?**\n\n### **Verdict: YES — with caveats.**  \n**Go ahead — but only if you can commit to a focused MVP (Minimum Viable Product) with clear boundaries.**\n\n### **Why YES?**\n- **High business value**: Early material selection reduces prototyping costs, accelerates time-to-market, and improves sustainability.\n- **Google Cloud is well-suited**: Strong AI/ML stack (Vertex AI), scalable data processing (BigQuery, Dataflow), and integration with engineering tools.\n- **Existing data likely exists**: Material databases (e.g., MatWeb, CES EduPack), historical test data, or CAD/FEA outputs can be leveraged.\n\n### **Why Caveats?**\n- **Data quality is critical**: If your team lacks curated, structured material-performance datasets, this project will stall.\n- **Domain expertise gap**: Material scientists/engineers must be deeply involved — AI can’t guess material behavior without physics-informed guidance.\n- **Scope creep risk**: "Predict performance under various conditions" is too broad. Must narrow to 2–3 key use cases.\n\n> 🚫 **Do NOT attempt** if:  \n> - You have no access to historical material test data or design outcomes.  \n> - No dedicated SME (Subject Matter Expert) from Product Development is available 10–15 hrs/week.  \n> - You expect a full generative AI “material recommender” with 95% accuracy in 4 months.\n\n> ✅ **DO proceed** if:  \n> - You can define 2–3 target use cases (e.g., “select lightweight, corrosion-resistant alloy for outdoor sensor housing under 80°C and 90% humidity”).  \n> - You have 500+ labeled material-performance records (even if noisy).  \n> - You can assign a cross-functional team: 1 Data Engineer, 1 ML Engineer, 1 Product Dev SME, 1 PM.\n\n---\n\n## 🚀 **High-Level Project Plan (4-Month Timeline)**  \n**Goal**: Deliver an MVP that recommends top 3 suitable materials for a given design constraint (e.g., stress, temperature, cost) with >80% accuracy on historical validation data.\n\n### **Phase 1: Discovery & Data Ingestion (Weeks 1–4)**  \n**Objective**: Confirm data availability, define scope, and build data pipeline.  \n- **Activities**:  \n  - Workshop with Product Dev to define **3 target use cases** (e.g., “motor housing,” “seal gasket,” “heat sink”).  \n  - Inventory existing data:  \n    - Internal: CAD specs, FEA results, material test logs (CSV/Excel/DB).  \n    - External: Open material databases (MatWeb, NIST, or purchase CES EduPack via Google Cloud Marketplace).  \n  - Define **features**: tensile strength, density, thermal conductivity, cost/kg, corrosion rating, manufacturability.  \n  - Build **BigQuery dataset** to unify data.  \n  - Use **Cloud Storage** to store raw files (PDFs, CAD exports).  \n- **Deliverable**: Curated dataset of 500–1,000 material-performance records + use case definitions.  \n\n### **Phase 2: Feature Engineering & Model Prototyping (Weeks 5–10)**  \n**Objective**: Build and validate a baseline ML model.  \n- **Activities**:  \n  - Use **Vertex AI Workbench** for Jupyter notebooks.  \n  - Engineer features: Normalize values, create composite scores (e.g., “cost-to-strength ratio”).  \n  - Label data: “Suitable” / “Unsuitable” based on historical design outcomes.  \n  - Train baseline models:  \n    - Random Forest (for interpretability)  \n    - XGBoost (for performance)  \n    - *Optional*: Graph Neural Network (if material relationships are networked, e.g., alloys → elements)  \n  - Use **Vertex AI Training** to scale training runs.  \n- **Deliverable**: Model achieving ≥75% accuracy on holdout test set for 1 use case.  \n\n### **Phase 3: MVP Build & Integration (Weeks 11–14)**  \n**Objective**: Deploy a simple web interface for engineers.  \n- **Activities**:  \n  - Deploy model as **Vertex AI Endpoint**.  \n  - Build UI with **Streamlit** (fast, Python-based) or **Cloud Run + React** (if scalable UI needed).  \n  - UI Inputs: User selects design constraints (e.g., max weight, temp

In [31]:
# Explore the first result's explanation
print(pairwise_result.metrics_table.loc[0,'pairwise_text_quality/explanation'])

BASELINE response provides a more detailed and specific project plan, particularly in its integration of Google Cloud services within each phase, which directly addresses the 'how a solution could be developed' instruction. Its 'Go/No-Go Assessment' is also more comprehensive and well-justified than CANDIDATE response's. Both responses unfortunately cut off abruptly due to token limits, but BASELINE response's content prior to the cut-off is marginally stronger in addressing the core aspects of the prompt.

## Test the CodeGemma deployment

In [32]:
import google.cloud.logging
import logging

from google.cloud import aiplatform

# Do not remove logging section
client = google.cloud.logging.Client()
client.setup_logging()


# Replace your project number and endpoint id

endpoint_resource_name=f"projects/PROJECT_NUMBER/locations/us-central1/endpoints/ENDPOINT_ID"
endpoint=aiplatform.Endpoint(endpoint_resource_name)

In [33]:

prompt = "Write a function to list n Fibonacci numbers in Python." 
max_tokens = 500 
temperature = 1.0 
top_p = 1.0  
top_k = 1 
raw_response = True

# instances = [
#     {
#      # Fill in the appropriate configuration
#     },
# ]
instances = [
    {
        "prompt": prompt,
        "max_tokens": max_tokens,
        "temperature": temperature,
        "top_p": top_p,
        "top_k": top_k,
        "raw_response": raw_response,
    }
]


response = endpoint.predict(
    instances=instances
)

# "<|file_separator|>" is the end of the file token.
for prediction in response.predictions:
    print(prediction.split("<|file_separator|>")[0])


print(response.deployed_model_id)

# Do not remove logging section
log_message = f"Fibonacci function: {response}"
logging.info(log_message)

py
<|fim_prefix|><|fim_suffix|><|fim_middle|>def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib_sequence = [0, 1]
        while len(fib_sequence) < n:
            next_number = fib_sequence[-1] + fib_sequence[-2]
            fib_sequence.append(next_number)
        return fib_sequence

n = int(input("Enter the number of Fibonacci numbers to generate: "))
fibonacci_numbers = fibonacci(n)
print(fibonacci_numbers)

4248548663854366720

## Perform Cleanup

In [34]:
# Delete all endpoints and their deployed models
endpoints = aiplatform.Endpoint.list()

if not endpoints:
    print("No endpoints found in this project/region.")
else:
    for endpoint in endpoints:
        print(f"\nEndpoint: {endpoint.display_name} ({endpoint.resource_name})")

        deployed_models = endpoint.list_models()
        for dm in deployed_models:
            print(f"  Undeploying model ID: {dm.id}")            
            # TODO Uncomment the statement below to undeploy a model
            endpoint.undeploy(deployed_model_id=dm.id, sync=True)
            print(f"  Undeployed model ID: {dm.id}")

        print("  Deleting endpoint...")
        endpoint.delete(sync=True)
        print(f"  Deleted endpoint: {endpoint.display_name}")

print("\nDeleting models...")
models = aiplatform.Model.list()

for model in models:
    print(f"  Deleting model: {model.display_name}")
    # TODO Uncomment the statement below to delete the model.
    model.delete(sync=True)
    print("  Deleted.")
    
# Do not remove logging section
log_message = "Deleted endpoints"
logging.info(log_message)

Endpoint: google_codegemma-2b-mg-one-click-deploy (projects/5399527077/locations/us-central1/endpoints/mg-endpoint-496aac9f-f7f6-42aa-83c2-b2f9ff9b445b)
  Undeploying model ID: 4248548663854366720
Undeploying Endpoint model: projects/5399527077/locations/us-central1/endpoints/mg-endpoint-496aac9f-f7f6-42aa-83c2-b2f9ff9b445b
Undeploy Endpoint model backing LRO: projects/5399527077/locations/us-central1/endpoints/mg-endpoint-496aac9f-f7f6-42aa-83c2-b2f9ff9b445b/operations/2412620964253663232
Endpoint model undeployed. Resource name: projects/5399527077/locations/us-central1/endpoints/mg-endpoint-496aac9f-f7f6-42aa-83c2-b2f9ff9b445b
  Undeployed model ID: 4248548663854366720
  Deleting endpoint...
Deleting Endpoint : projects/5399527077/locations/us-central1/endpoints/mg-endpoint-496aac9f-f7f6-42aa-83c2-b2f9ff9b445b
Endpoint deleted. . Resource name: projects/5399527077/locations/us-central1/endpoints/mg-endpoint-496aac9f-f7f6-42aa-83c2-b2f9ff9b445b
Deleting Endpoint resource: projects/5399527077/locations/us-central1/endpoints/mg-endpoint-496aac9f-f7f6-42aa-83c2-b2f9ff9b445b
Delete Endpoint backing LRO: projects/5399527077/locations/us-central1/operations/128170053269979136
Endpoint resource projects/5399527077/locations/us-central1/endpoints/mg-endpoint-496aac9f-f7f6-42aa-83c2-b2f9ff9b445b deleted.
  Deleted endpoint: google_codegemma-2b-mg-one-click-deploy

Deleting models...
  Deleting model: google_codegemma-2b-1770264338962
Deleting Model : projects/5399527077/locations/us-central1/models/google_codegemma-2b-1770264338962
Model deleted. . Resource name: projects/5399527077/locations/us-central1/models/google_codegemma-2b-1770264338962
Deleting Model resource: projects/5399527077/locations/us-central1/models/google_codegemma-2b-1770264338962
Delete Model backing LRO: projects/5399527077/locations/us-central1/models/google_codegemma-2b-1770264338962/operations/2869736326431768576
Model resource projects/5399527077/locations/us-central1/models/google_codegemma-2b-1770264338962 deleted.
  Deleted.